[package]
name = "challenge_1_2"
version = "0.1.0"
authors = ["Sam Bukowski <sam.c.bukowski@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
